@startuml
!define RECTANGLE(x) rectangle x

' Colores para categorías
!define COLOR_USUARIOS #FFFF00
!define COLOR_SISTEMA #D3D3D3
!define COLOR_NOTIFICACIONES #FFCC99

' Definición de actores y módulos del sistema con colores
RECTANGLE(CIUDADANO) #FFFF00
RECTANGLE(FUNCIONARIO) #FFFF00
RECTANGLE(SISTEMA) #D3D3D3
RECTANGLE(NOTIFICACIONES) #FFCC99

' Relaciones entre los actores y los módulos del sistema
CIUDADANO --> NOTIFICACIONES : Recibir notificación
FUNCIONARIO --> NOTIFICACIONES : Enviar notificación
NOTIFICACIONES --> SISTEMA : Gestionar notificaciones
NOTIFICACIONES --> CIUDADANO : Notificar cambios en cita
NOTIFICACIONES --> FUNCIONARIO : Notificar cancelación o modificación de cita
@enduml
