@startuml Diagrama de Contexto (Ciudadano)

skin rose
skinparam note{
  BackgroundColor white
}
title Diagrama de Contexto (Ciudadano)

[*] --> INICIO

INICIO -d-> PANEL_CIUDADANO
note on link: accesoPanel

PANEL_CIUDADANO -d-> CONSULTA_ESTADO_CITA
CONSULTA_ESTADO_CITA -u-> PANEL_CIUDADANO
note on link: consultarEstadoCita

CONSULTA_ESTADO_CITA -d-> NOTIFICACION_ESTADO
NOTIFICACION_ESTADO -u-> CONSULTA_ESTADO_CITA
note on link: mostrarEstado

NOTIFICACION_ESTADO -r-> OPCION_REPROGRAMAR
OPCION_REPROGRAMAR -l-> NOTIFICACION_ESTADO
note on link: ofrecerReprogramar

PANEL_CIUDADANO -d-> [*]
CONSULTA_ESTADO_CITA --> [*]
NOTIFICACION_ESTADO --> [*]
OPCION_REPROGRAMAR --> [*]

@enduml
