@startuml
!define RECTANGLE(x) rectangle x

' Definición de los colores personalizados
!define COLOR_CIUDADANO #FFFF00
!define COLOR_SISTEMA #D3D3D3

' Definición de los actores y módulos del sistema con colores
RECTANGLE(CIUDADANO) COLOR_CIUDADANO
RECTANGLE(Panel_ciudadano) COLOR_SISTEMA

' Relaciones entre el ciudadano y el sistema
CIUDADANO --> Panel_ciudadano : Consultar estado de cita
Panel_ciudadano --> CIUDADANO : Mostrar estado\n+ Notificación
Panel_ciudadano --> CIUDADANO : Ofrecer opción de reprogramar

@enduml

