@startuml
' Definición de rectángulos con colores
rectangle CIUDADANO #FFFF00
rectangle Panel_ciudadano #D3D3D3

' Relaciones
CIUDADANO --> Panel_ciudadano : Consultar estado de cita
Panel_ciudadano --> CIUDADANO : Mostrar estado\n+ Notificación
CIUDADANO <-- Panel_ciudadano : Ofrecer opción de reprogramar
CIUDADANO --> Panel_ciudadano : Continuar en el panel
@enduml
