@startuml CdU_ConsultarEstadoCita
left to right direction

actor "Ciudadano" as Ciudadano

rectangle {
    usecase "Ingresar datos para consulta" as IngresarDatosParaConsulta
    usecase "Validar datos" as ValidarDatos
    usecase "Mostrar estado de cita" as MostrarEstadoDeCita
    usecase "Enviar notificación" as EnviarNotificacion
    usecase "Ofrecer opción de reprogramar" as OfrecerOpcionDeReprogramar
}

Ciudadano --> IngresarDatosParaConsulta
Ciudadano --> ValidarDatos
Ciudadano --> MostrarEstadoDeCita
Ciudadano --> EnviarNotificacion
Ciudadano --> OfrecerOpcionDeReprogramar

@enduml
