@startuml EliminarFuncionario
state "DASHBOARD_ABIERTO" as DASHBOARD_ABIERTO

DASHBOARD_ABIERTO --> Eliminar
Eliminar --> DASHBOARD_ABIERTO

state Eliminar {
  [*] -[#blue]-> seleccionarFuncionarioEliminar
  state "Seleccionar funcionario" as seleccionarFuncionarioEliminar
  seleccionarFuncionarioEliminar -[#blue]-> confirmarEliminacionFuncionario
  note on link
    **El sistema requiere**:
    ° Seleccionar el funcionario que desea eliminar
  end note

  state "Confirmar eliminación" as confirmarEliminacionFuncionario
  confirmarEliminacionFuncionario -[#blue]-> [*]
  note on link: **El usuario solicita** confirmar la eliminación

  seleccionarFuncionarioEliminar -[#red]-> [*]
  note on link: **El usuario solicita** cancelar la eliminación
}
@enduml

