@startuml Diagrama de Contexto (Consulta de Cita - Ciudadano)

skin rose
skinparam note{
  BackgroundColor white
}
title Diagrama de Contexto (Ciudadano - Consulta de Cita)

[*] --> INICIO

INICIO -d-> PANEL_CIUDADANO
note on link: accesoPanel

PANEL_CIUDADANO -r-> CONSULTAR_ESTADO_CITA
CONSULTAR_ESTADO_CITA -l-> PANEL_CIUDADANO
note on link: consultarEstadoCita

CONSULTAR_ESTADO_CITA -d-> MOSTRAR_ESTADO
MOSTRAR_ESTADO -u-> CONSULTAR_ESTADO_CITA
note on link: mostrarEstado

MOSTRAR_ESTADO -r-> NOTIFICACION
NOTIFICACION -l-> MOSTRAR_ESTADO
note on link: notificarCiudadano

NOTIFICACION -r-> OPCION_REPROGRAMAR
OPCION_REPROGRAMAR -l-> NOTIFICACION
note on link: ofrecerReprogramación

PANEL_CIUDADANO -d-> [*]
CONSULTAR_ESTADO_CITA --> [*]
MOSTRAR_ESTADO --> [*]
NOTIFICACION --> [*]
OPCION_REPROGRAMAR --> [*]

@enduml


