@startuml Diagrama de Contexto (Usuarios y Sistema)

skin rose
skinparam note {
  BackgroundColor white
}
title Diagrama de Contexto (Usuarios)

[*] --> USUARIO_NO_REGISTRADO

USUARIO_NO_REGISTRADO -d-> REGISTRO_USUARIO
note on link: registrar

REGISTRO_USUARIO -r-> USUARIO_REGISTRADO
note on link: éxitoRegistro

USUARIO_REGISTRADO -d-> MODULO_CITAS
MODULO_CITAS -u-> USUARIO_REGISTRADO
note on link: solicitarCita

USUARIO_REGISTRADO -r-> MODULO_NOTIFICACIONES
MODULO_NOTIFICACIONES -l-> USUARIO_REGISTRADO
note on link: recibirNotificaciones

USUARIO_REGISTRADO -d-> NAVEGACION_SISTEMA
NAVEGACION_SISTEMA -u-> USUARIO_REGISTRADO
note on link: navegarSistema

MODULO_CITAS --> [*]
MODULO_NOTIFICACIONES --> [*]
NAVEGACION_SISTEMA --> [*]

@enduml
