@startuml
class Usuario {
}

class Ciudadano {
}

class Funcionario {
}

class Administrador {
}

class Cita {
}

class Oficina {
}

class Notificación {
}

Usuario -- Ciudadano
Usuario -- Funcionario
Usuario -- Administrador

Ciudadano -- Cita : "solicita"
Funcionario -d- Cita : "gestiona"

Oficina -- Cita : "asignada a"
Oficina -u- Funcionario : "trabaja en"

Cita -- Notificación : "genera"

Notificación -u- Ciudadano : "notifica"
Notificación -u- Funcionario : "notifica"
@enduml
