@startuml Modelos

package "Modelos" {
    entity Usuario
    entity Cita
    entity Ciudadano
    entity Oficina
    entity Notificacion
    entity Administrador
    entity Horario
    entity Funcionario
}

@enduml
